version: '3.8'

services:
  # 后端服务
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mintai-dialect-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
      - ./backend/models:/app/models
    environment:
      - DATABASE_URL=sqlite:///./dialect_ai.db
      - DEBUG=false
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - mintai-network

  # 前端服务 (生产环境)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mintai-dialect-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    restart: unless-stopped
    networks:
      - mintai-network

  # Nginx反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: mintai-dialect-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL证书目录
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - mintai-network

networks:
  mintai-network:
    driver: bridge

volumes:
  uploads:
  logs:
  models: 